create database colleges;
create database marks;
 use colleges;
 create table students_details(rollno int primary key, name varchar(20),age int);
 select * from students_details;
 insert into students_details values(101,"Adithya",23);
 insert into students_details values(102,"Brian",24);
 insert into students_details values(103,"Jeol",23);
 insert into students_details values(104,"Hema",23);
 drop table students_details;
 create database company;
 use company;
 create table company_detials(employeeid int primary key, name varchar(20)not null,salary int default 25000,age int);
 select * from company_detials;
 insert into company_detials values(1001,"Adithya",25000,23);
 insert into company_detials values(1002,"Bhumika",15000,24);
 insert into company_detials values(1003,"Hema",25000,23);
 insert into company_detials values(1004,"Brian",30000,24);
 drop table company_detials;
 create table department(dept_id int primary key,dept_name varchar(30));
 insert into department values(201,"HR");
 insert into department values(202,"BA");
 insert into department values(203,"Finance");
 insert into department values(204,"Dev");
 select * from department;
create table employees(emp_id int primary key,emp_name varchar(30),salary int default 28000,department_id int,foreign key(department_id)references department(dept_id));
insert into employees values(1,"Adithya",30000,201);
insert into employees values(2,"Hema",40000,202);
insert into employees values(3,"Joel",35000,203);
insert into employees values(4,"Brian",29000,204);
select * from employees;
drop table employees;
select emp_name from employees where salary>34000;
select emp_name from employees where salary<40000;
select emp_name from employees where department_id>202;
select emp_name from employees where department_id=202;
select emp_name from employees where department_id!=202;
select emp_id from employees where salary>=35000;
select emp_name from employees where department_id=201 AND department_id=203;
select emp_name from employees where department_id=201 or department_id=203;
select emp_name from employees where department_id=201 and salary>34000;
select emp_name from employees where not salary=40000;
select * from employees where salary+70000>100000;
select max(Salary) from employees;
select min(Salary) from employees;
select sum(Salary) from employees;
select avg(Salary) from employees;
select count(Salary) from employees;
create table Student_Table(id int primary key,name varchar(30));
insert into Student_Table values(101,"Adithya");
insert into Student_Table values(102,"Hema");
insert into Student_Table values(103,"Joel");
insert into Student_Table values(104,"Bhumika");
select * from Student_Table;
create table Student_Course(id int, course varchar(40));
insert into Student_Course values(101,"HR");
insert into Student_Course values(102,"BA");
insert into Student_Course values(103,"FM");
insert into Student_Course values(104,"BE");
select * from Student_Course;
select Student_Table.name,Student_Course.course from Student_Table inner join course on Student_Table.id=Student_Course.id;